function init(self)
	-- 1. Анимация затухания
	go.animate("#sprite", "tint.w", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_OUTSINE, 0.4)

	-- 2. Анимация масштаба и удаление
	go.animate(".", "scale", go.PLAYBACK_ONCE_FORWARD, vmath.vector3(0.5, 0.5, 1), go.EASING_OUTSINE, 0.4, 0, function()
		go.delete()
	end)

	-- 3. ЦЕПНАЯ РЕАКЦИЯ: Проверка объектов в момент появления
	-- Мы делаем микро-проверку физикой прямо в точке спавна огня
	--local pos = go.get_position()
	-- Ищем объекты групп "explosive" (бомбы, мины, динамит)
-- 	local hits = physics.raycast(pos, pos + vmath.vector3(0.1, 0, 0), { hash("bomb") , hash("mine")})
-- 
-- 	print(hits)
-- 	if hits then
-- 		-- Если нашли взрывчатку — подрываем её
-- 		msg.post(hits.id, "detonate")
-- 	end
end

function on_message(self, message_id, message, sender)
	-- Урон по игроку и врагам через триггер
	if message_id == hash("trigger_response") then
		if message.enter then
			if message.other_group == hash("player") then
				msg.post(message.other_id, "take_damage", { amount = 1 })
			elseif message.other_group == hash("enemy") then
				msg.post(message.other_id, "die")
			end
		end
	end
end